[package]
name = "gdlogue"
version = "0.1.0"
edition = "2018"

[dependencies]
serde = {version = "1.0.130", features=["derive"]}
serde_json = "1.0.64"
thiserror = "1.0.25"
which = "4.1.0"

[[bin]]
name = "gdlogue"
path = "src/bin.rs"

[lib]
name = "gdlogue"
path = "src/lib.rs"
